export const cardygan = {
	"name": "Cardygan",
	"products": [
		{
			"id": "CAE-OSAKA",
			"name": "Osaka Sweater",
			"slug": "cardygan-osaka-sweater-elogiefemale-elogie",
			"price": 95000,
			"discount": 0,
			"brand": "",
			"color": "",
			"material": "",
			"category": "Cardygan",
			"description": "\nPanjang Baju : 61cm \nLingkar Dada : Free \nPanjang Lengan : 49cm \nLingkar Lengan : 44cm \n\nAllsize (Fit atau muat kira2 dari ) S - XL\n\n* Warna : Army, Bronze, Cream, Mocca, Plum\n* Bahan : Rajut Premium\n* Berat : 350gr\n*Karakteristik lain : Tidak berkancing, Ada Kerutan Bag Tangan",
			"variants": {
				"name": "Warna",
				"variant": [
					{"id": 0, "name": "All", 		"stock": 20, "production": 100, "imageId": 0},
					{"id": 1, "name": "Army", 	"stock": 5, "production": 100, "imageId": 0},
					{"id": 2, "name": "Bronze","stock": 5, "production": 100, "imageId": 4},
					{"id": 3, "name": "Cream", "stock": 5, "production": 100, "imageId": 6},
					{"id": 4, "name": "Mocca", "stock": 5, "production": 100, "imageId": 9},
					{"id": 5, "name": "Plum", 	"stock": 5, "production": 100, "imageId": 12},
				],
			},
			"images": [
				{"id": 0, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fHL1Nzgazje4LL8fHi3Wb1HI2LrcGRsKJYpZPtGp3A.webp"},
				{"id": 1, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fHh7Z5iuLw8CfQkfHi33AjRiYEdqQFSh2YeZZKdO7GZQ.webp"},
				{"id": 2, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fHfgWQO0CBd3J06JfHi33dwgLEfurppRCOcqrmff2bfCw.webp"},
				{"id": 3, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fHCAepqakh40TJfHi33BWtWKy2Xy2Rru1sbXCbIQ0UQ.webp"},
				{"id": 4, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fH8x6q4Ay3wNCvYfHi33yioWpm2WN1Spq3vqH1nTKhyQ.webp"},
				{"id": 5, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fHhI0F34o17PbsfHi33aJTWBuGKLXTYS2nOtTGZEU6A.webp"},
				{"id": 6, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fHLHy2C0hs8pEhBxfHi34HSKON0NBbSi6ToH8MsO3g.webp"},
				{"id": 7, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fH8xPC8fnyTILK1fHi343RERBtFXISdyhhfTeW8w0g.webp"},
				{"id": 8, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fHCFm1k1n3YniqWfHi34Nwv2eWDGOORsarDIRYUlPzcg.webp"},
				{"id": 9, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fH8xvzOl1C4GlPfHi345AbonLk4rvSfmUyPRcG5Bsgw.webp"},
				{"id": 10, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fHCKKxWFEy3YLzPfHi3uhBTeEVWJ0T6SKAu6yUFDiw.webp"},
				{"id": 11, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fHhwJS54nJwqHjofHi3umvMQ54rfRqTcGTDqDNebcCQ.webp"},
				{"id": 12, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fs9omvI0CZAEM0nIfHi3urwIh2khmXaQS20CKV6qeGh6Q.webp"},
				{"id": 13, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fHL1ZOqGxgU2faFfHi3uwXlwpTUjVvSbeVYekM6kouKg.webp"},
				{"id": 14, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fH0l8HGZ9wpD099fHi3uehOuW23Ov7RW1DP6qItBvtA.webp"},
			]
		},
		{
			"id": "CAE-TOKYO",
			"name": "Tokyo Sweater",
			"slug": "cardygan-tokyo-sweater-elogiefemale-elogie",
			"price": 95000,
			"discount": 0,
			"brand": "",
			"color": "",
			"material": "",
			"category": "Cardygan",
			"description": "\nPanjang Baju : 62cm \nLingkar Dada : Free \nPanjang Lengan : 45cm \nLingkar Lengan : 40cm \nAllsize (Fit atau muat kira2 dari ) S - XL \n\n* Warna : Bronze, Cream, Maroon, Matcha, Plum, Avocado\n*Bahan : Rajut Premium\n*Karakteristik lain : Tidak berkancing, ada saku",
			"variants": {
				"name": "Warna",
				"variant": [
					{"id": 0, "name": "All", 								"stock": 20,"production": 100, "imageId": 0},
					{"id": 1, "name": "Plum", 							"stock": 5, "production": 100, "imageId": 7},
					{"id": 2, "name": "Macha", 						"stock": 5, "production": 100, "imageId": 5},
					{"id": 3, "name": "Cream", 						"stock": 5, "production": 100, "imageId": 9},
					{"id": 4, "name": "Bronze", 					"stock": 0, "production": 100, "imageId": 0},
					{"id": 5, "name": "Maroon", 					"stock": 0, "production": 100, "imageId": 2},
					{"id": 6, "name": "Avocado", 				"stock": 5, "production": 100, "imageId": 9},
					{"id": 7, "name": "Broken White","stock": 0, "production": 100, "imageId": 14},
				],
			},
			"images": [
				{"id": 0, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/K4t3GYwBGvlSDCrg8Rh3CP6.webp"},
				{"id": 1, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/ANMuQHuuHDPTeehm44BpTDo.webp"},
				{"id": 2, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/hUwDBt2c37qwxBSs8SqV9scv.webp"},
				{"id": 3, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/BJBATazrWRZ84CTUKHS5CHXX.webp"},
				{"id": 4, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/hWSNsxHpi0gMECozhjii3mIi.webp"},
				{"id": 5, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/Xz3j3pqq1Z1y63wmGDzEd6m.webp"},
				{"id": 6, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/7yuFMPxDD1huOvqTVA849.webp"},
				{"id": 7, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/z3tkhIiW2avkyAhGhOr5xmj.webp"},
				{"id": 8, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/StCkmRVpbh5KQ6sbByV1skW.webp"},
				{"id": 9, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/wzXLUjzZeXyArWsGKScfL8.webp"},
				{"id": 10, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fimLOgEdM6SeH4AfiRxOM6hkWFVuz6Qavkcv0rufh0Q.webp"},
				{"id": 11, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fimLOkyu715VhvGfiRxOZGbQJLDytyRjqItsgVhlgQ.webp"},
				{"id": 12, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fimLO6PAKZ4WcffiRxOJy44SGEjzHRauHCy6eeFRHpg.webp"},
				{"id": 13, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fimLjDJJM0luHfNfiRxOeRNCLWlNS1TauEeCx5T9135g.webp"},
				{"id": 14, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fimLXjiDaBXKLaOfiRxjLWpSyY6YlNS9ya4MQmIa6eMw.webp"},
			]
		}
	]
}