module.exports = {
	"name": "Celana",
	"products": [
		{
			"id": "CEE-LIORA",
			"name": "Liora Pants",
			"slug": "celana-liora-pants-elogiefemale-elogie",
			"price": 109000,
			"discount": 0,
			"brand": "",
			"color": "",
			"material": "",
			"category": "Celana",
			"description": "\n \nPanjang Celana Bag. Depan : 79cm \nPanjang Celana Bag. Belakang : 84cm \nLingkar Paha : 56cm \nLingkar Pinggang : 70cm \nLingkar Pinggang Saat Ditarik : 104cm \n\nAllsize (Fit atau muat kira2 dari ) S - XL \n\n* Warna : Black, Dusty Pink, Grey, White \n*Bahan : Scuba Premium \n* Berat :  250gr  \n*Karakteristik lain : Bagian pinggang full karet, Karakter kain elastis",
			"variants": {
				"name": "Warna",
				"variant": [
					{"id": 0, "name": "All", 						"stock": 6, "production": 100, "imageId": 0},
					{"id": 1, "name": "Black",					"stock": 0, "production": 100, "imageId": 8},
					{"id": 2, "name": "Dusty Pink","stock": 5, "production": 100, "imageId": 4},
					{"id": 3, "name": "Grey", 					"stock": 0, "production": 100, "imageId": 5},
					{"id": 4, "name": "White", 				"stock": 1, "production": 100, "imageId": 1},
				],
			},
			"images": [
				{"id": 0, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fipusUhPK4wCLSMfiPYftbZ4Am6UQwSTaEiDgt8Waow.webp"},
				{"id": 1, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fsR4GFB5szU7CKjfsWyzqClMTZB6PQquK0jvWgD9NtA.webp"},
				{"id": 2, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fskDrJo6woUyfAcfsWyz98dQSBTY2pQfmNVen1MlFg.webp"},
				{"id": 3, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fsd3mncgxpbo0eefsWy5h9ArksXdIWSTJek33MWV5vQ.webp"},
				{"id": 4, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fska5dDRKAMLfQQfsWy5K4mvIaaXTqRCacXkcdmKRByg.webp"},
				{"id": 5, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fsTrbZJHX5wmiCWfsWy5XM8aryvl8iTauPsUebG8s20g.webp"},
				{"id": 6, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fsR6uVIl6VhjWjfsWy5WTeqPaPXPtRgmzgOIm95aaSA.webp"},
				{"id": 7, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fskUjH7rvZpz0ExfsWy5SYIBGO7jmhS9Ke1NEsYnY1A.webp"},
				{"id": 8, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fskagar71WCMLWhfsWy5Qz61lKaYaGQiiLfbXkegqKmQ.webp"},
			],
		},
		{
			"id": "CEE-NAOMI",
			"name": "Naomi Pleated Pants",
			"slug": "celana-naomi-pleated-pants-elogiefemale-elogie",
			"price": 90000,
			"discount": 0,
			"brand": "",
			"color": "",
			"material": "",
			"category": "Celana",
			"description": "\nPanjang Celana : 96cm \nLingkar Pinggang : 64cm\nLingkar Pinggang Saat Karet Melar : 100cm\nLingkar Paha : 86cm\nAllsize (Fit atau muat kira2 dari ) S - XL \n\n* Warna : Black, Coco, Grey, Cream\n*Bahan : Amuzen, Halus dan jatuh \n\n*Mirip seperti carissa tapi ini celana. Sama Chelsea Palazzo lebih lebar ini",
			"variants": {
				"name": "Warna",
				"variant": [
					{"id": 0, "name": "All", 	"stock": 13, "production": 100, "imageId": 0},
					{"id": 1, "name": "Army", "stock": 5, 	"production": 100, "imageId": 3},
					{"id": 2, "name": "Black","stock": 0, 	"production": 100, "imageId": 6},
					{"id": 3, "name": "Coco", "stock": 3, 	"production": 100, "imageId": 7},
					{"id": 4, "name": "Cream","stock": 5, 	"production": 100, "imageId": 5},
				],
			},
			"images": [
				{"id": 0, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fAgEcnkPnk2ahKAfAzVX4hh3pQGQc4TnORIGrpVxS9Ew.webp"},
				{"id": 1, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fAZt6vGqJRGkCbEfAzVjZ85CBcvT85SpdtmUQ5BcvWw.webp"},
				{"id": 2, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fAlGHhHFOQZiieffAzVjGr0vhuH2DITX62M1pXnYOUw.webp"},
				{"id": 3, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LaZ3X7E.webp"},
				{"id": 4, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LaZ3RiP.webp"},
				{"id": 5, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LaZ3vfn.webp"},
				{"id": 6, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LaZ3pCd.webp"},
				{"id": 7, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LaZ3FLV.webp"},
				{"id": 8, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LaZ3QXj.webp"},
				{"id": 9, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/q0zeNWJ2WWkyPoAfyPHHZGF.webp"},
				{"id": 10, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fAZeFNUT31YBHBxfAzVXfELn9sGwcnSzeS1F9hcoGMw.webp"},
				{"id": 11, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/fAZt9s9KwL7bnTfAzVXHaaHhgwXciQouDGczXx9Wzg.webp"},
			],
		},
		{
			"id": "CEE-FIONA",
			"name": "Fiona Palazzo",
			"slug": "celana-fiona-palazzo-elogiefemale-elogie",
			"price": 105000,
			"discount": 0,
			"brand": "",
			"color": "",
			"material": "",
			"description": "\nPanjang Celana : 98cm \nLingkar Pinggang : 70cm \nLingkar Pinggang saat di tarik : 106cm \nLingkar Paha : 62cm \n\n* Warna : White, Black \n*Bahan Scuba Premium (Tebal, Halus) \n*Ada saku kanan kiri",
			"variants": {
				"name": "Warna",
				"variant": [
					{"id": 0, "name": "All", "stock": 6, "imageId": 0},
					{"id": 1, "name": "White", "stock": 5, "imageId": 0},
					{"id": 2, "name": "Black", "stock": 1, "imageId": 3}
				],
			},
			"images": [
				{"id": 0, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LJxmCAT.webp"},
				{"id": 1, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LJxXh2.webp"},
				{"id": 2, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LJxmhfg.webp"},
				{"id": 3, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LJxXYsN.webp"},
				{"id": 4, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LJxXc0l.webp"},
				{"id": 5, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LJxXosz.webp"},
				{"id": 6, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LJxXgXC.webp"}
			]
		},
		{
			"id": "CEE-RETRO",
			"name": "Retro Cutbray",
			"slug": "celana-retro-cutbray-elogiefemale-elogie",
			"price": 95000,
			"discount": 0,
			"brand": "",
			"color": "",
			"material": "",
			"description": "\nPanjang Celana 97cm\nLingkar Paha 86cm (jika ditarik) \nLingkar Pinggang 72cm\nLingkar Pinggang saat ditarik 102cm\nAll Size fit S- XL  \n\n* Bahan wedges tebal halus \n* Warna : Black, White",
			"variants": {
				"name": "Warna",
				"variant": [
					{"id": 0, "name": "All", "stock": 10, "imageId": 0},
					{"id": 1, "name": "White", "stock": 5, "imageId": 0},
					{"id": 2, "name": "Black", "stock": 5, "imageId": 3}
				],
			},
			"images": [
				{"id": 0, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LJlJcfC.webp"},
				{"id": 1, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LJlY0R.webp"},
				{"id": 2, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LJlJ6sE.webp"},
				{"id": 3, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LJlbIT.webp"},
				{"id": 4, "url": "https://img.bdjkt.com/img/1200/bfz2vqtcbf13p9qiru/LJlJLO.webp"},
			],
		},
	]
}